/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package sharedlibrary

class Library {
    def call() {
        stage('First') {
            print "First stage"
        }
        stage('Second') {
            print "Second stage"
        }
        stage('Third') {
            print "Third stage"
        }
        stage('Fourth') {
            print "Fourth stage"
        }
        stage('Fifth') {
            print "Fifth stage"
        } 
    }
}
